### ISSUE TITLE
command_name not set / update for 2.5

### ISSUE THREAD

**Issue by tobixx** [coddingtonbear/taskwarrior-capsules#1]
On task version 2.5.1

```
Traceback (most recent call last):
  File "/home/x/.local/bin/tw", line 11, in <module>
    sys.exit(main())
  File "/home/x/.local/lib/python2.7/site-packages/taskwarrior_capsules/cmdline.py", line 94, in main
    terminal=term,
  File "/home/x/.local/lib/python2.7/site-packages/taskwarrior_capsules/capsule.py", line 159, in execute
    self.validate(**kwargs)
  File "/home/x/.local/lib/python2.7/site-packages/taskwarrior_capsules/capsule.py", line 76, in validate
    self.command_name,
AttributeError: 'Blocks' object has no attribute 'command_name'
```

Probably related to:

```
/home/x/.local/lib/python2.7/site-packages/taskwarrior_capsules/capsule.py:79: UserWarning: Capsule 'add' is not compatible with version 2.5.1 of taskwarrior; minimum version: 2.2; maximum version 2.4.9999.
```

after I at least got it back to work with:

```
    def execute(
        self, variant, command_name, filter_args, extra_args, **kwargs
    ):
        self.command_name = command_name
```

Btw: is this project still alive ?

**Comment by NGenetzky** [comment]
> Btw: is this project still alive ?

No, I do not think it is. I would suggest checking out [taskpirate](https://github.com/tbabej/taskpirate).
