### ISSUE TITLE
Capsules do not work - lot of errors

### ISSUE THREAD

**Issue by hutou** [coddingtonbear/taskwarrior-capsules#2]
Hi,
I am trying to use capsules (for subtasks notably), but I encounter lot of errors.
Installation via sudo works fine :
```
sudo pip install taskwarrior-capsules
sudo pip install taskwarrior-subtask-capsule
```

On use, I first got errors because of missing parenthesis around the print function arguments.
After correcting this and trying to create a subtask, I got
```
$ tw 33 subtask hello
Traceback (most recent call last):
  File "/usr/bin/tw", line 11, in <module>
    load_entry_point('taskwarrior-capsules==0.3.2', 'console_scripts', 'tw')()
  File "/usr/lib/python3.7/site-packages/taskwarrior_capsules/cmdline.py", line 107, in main
    terminal=term,
  File "/usr/lib/python3.7/site-packages/taskwarrior_capsules/capsule.py", line 159, in execute
    self.validate(**kwargs)
  File "/usr/lib/python3.7/site-packages/taskwarrior_capsules/capsule.py", line 66, in validate
    tw_version = self.get_taskwarrior_version()
  File "/usr/lib/python3.7/site-packages/taskwarrior_capsules/capsule.py", line 19, in get_taskwarrior_version
    return NormalizedVersion(taskwarrior_version)
  File "/usr/lib/python3.7/site-packages/verlib.py", line 86, in __init__
    self._parse(s, error_on_huge_major_num)
  File "/usr/lib/python3.7/site-packages/verlib.py", line 95, in _parse
    match = VERSION_RE.search(s)
TypeError: cannot use a string pattern on a bytes-like object
```
My python skills are very low, do please, can you help ?

```
$ task --version
2.5.1

$ python --version
Python 3.7.2
```

**Comment by NGenetzky** [comment]
> sudo pip install taskwarrior-capsules
> sudo pip install taskwarrior-subtask-capsule

- Please stop installing with sudo.

> On use, I first got errors because of missing parenthesis around the print function arguments.

That is the first indicator that a python library lacks python3 support. Install with python2

---

```
python2 -m pip install --user taskwarrior-capsules taskwarrior-subtask-capsule
```
